(define (problem teste3)
    (:domain agenteSeguranca)
    (:objects Corredor Sala1 Porta1 Janela1 Sala2 Porta2 Janela2)
    (:init (Sala Corredor) (Em Corredor)
      (Sala Sala1)
      (Porta Porta1) (Pertence Sala1 Porta1) (Pertence Corredor Porta1)
      (Janela Janela1) (Pertence Sala1 Janela1)
      (Sala Sala2)
      (Porta Porta2) (Pertence Sala2 Porta2) (Pertence Corredor Porta2)
      (Janela Janela2) (Pertence Sala2 Janela2)
      (Aberta Porta1) (Aberta Janela1)
      (Aberta Porta2) (Aberta Janela2)
      (Conectadas Corredor Sala1)
      (Conectadas Corredor Sala2)
    )
    (:goal (and (not(Aberta Janela1)) (not(Aberta Porta1)) (not(Aberta Janela2)) (not(Aberta Porta2)) ))
)
