(define (problem fecharTudo)
    (:domain agenteSeguranca)
    (:objects Corredor Sala1 Sala2 Sala3 Sala4 Sala5 Sala6)
    (:init (Em Corredor) (Sala Corredor) (Sala Sala1) (Sala Sala2) (Sala Sala3) (Sala Sala4) (Sala Sala5) (Sala Sala6) (PortaAberta Sala1) (PortaAberta Sala2) (PortaAberta Sala3) (PortaAberta Sala4) (PortaAberta Sala5) (PortaAberta Sala6) (JanelaAberta Sala1) (JanelaAberta Sala2) (JanelaAberta Sala3) (JanelaAberta Sala4) (JanelaAberta Sala5) (JanelaAberta Sala6))
    (:goal (and(Em Corredor) (PortaFechada Sala1) (JanelaFechada Sala1) (PortaFechada Sala2) (JanelaFechada Sala2) (PortaFechada Sala3) (JanelaFechada Sala3) (PortaFechada Sala4) (JanelaFechada Sala4) (PortaFechada Sala5) (JanelaFechada Sala5) (PortaFechada Sala6) (JanelaFechada Sala6)))
)